### ISSUE TITLE
[Bug] Workspaces no longer works

### ISSUE THREAD

**Issue by astranberg** [vsmejkal/chrome-workspaces#10]
Hello,

My workspaces no longer works. I can click on the button and click on a given workspace, but no tabs will open. This occurs for all workspaces.

Using MS Edge on W10.

Thanks

**Comment by vsmejkal** [comment]
Hello, 

Thanks for reporting this issue. Sorry about that.

Could you please provide your version of the Workspaces extension?
1. Go to [edge://extensions/](edge://extensions/)
2. Enable **Developer mode**
3. You should see it next to the Workspaces title

Could you please also check if there are any errors in the _service worker_ console?
![image](https://user-images.githubusercontent.com/3717255/145489807-ba6e4a1f-8341-41f2-b71d-77420fc2ca6e.png)

Have your tried to restart the browser if it solves the issue?

**Comment by astranberg** [comment]
Very strange what just happened:
- Workspaces says "service worker (inactive) under the extension details.
- Clicking on details --> service worker popped up the devtools window. Nothing appears at first.
- When I click the extension and a workspace, a new window opened up and then my PC crashed. (perhaps this was a memory leak issue?)
- After reboot, opened Edge and clicked on extension, but nothing happens. No workspaces menu pops up.
- Turned extension on and off. Clicked the extension icon and still nothing.
- Clicked to open the service worker, and magically the extension loaded up. It now works as expected.

I'm sure there's a bug in here, but unfortunately I didn't capture anything. If there's anything else I can provide, please let me know.

**Comment by vsmejkal** [comment]
That's very strange. Looks to me more like a browser/hardware issue.

I would need the precise steps how to reproduce it. Otherwise I am not able to fix it.
How many tabs did you have in your workspace?
Were you doing anything specific when the problem occured?

**Comment by astranberg** [comment]
I've actually had the issue recur at least two more times. Disabling and reenabling the plug-in has worked recently.

This is all on the same computer. Btw.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vsmejkal** [comment]
Could not reproduce it. Please open a new issue if it occurs again.

**Comment by ioneliabuzatu** [comment]
I have the same issue as @astranberg described above. 

I have the previous tabs-group created but it does not open any longer. 

![image](https://github.com/vsmejkal/chrome-workspaces/assets/33060637/49f08410-be5b-4878-8c99-13c91e8606ce)
