### ISSUE TITLE
Menu Size

### ISSUE THREAD

**Issue by teamayu** [vsmejkal/chrome-workspaces#11]
Any chance a future update could reduce the menu font size or make the menu wider? The font is that big you can only use a few characters or else the title is truncated and you can't see what it is if you have similar named items.

Apart from that, works great, thank you.

**Comment by vsmejkal** [comment]
Hi, this has been already implemented and will be released in the upcoming version. Thanks for feedback.

**Comment by vsmejkal** [comment]
Implemented in v0.6.
