### ISSUE TITLE
Restore full-screen window

### ISSUE THREAD

**Issue by lazymonkey2** [vsmejkal/chrome-workspaces#15]
Hello,
when I close a workspace window, and then reopen the workspace, the previous full-screen status of the window is not restored:
I always keep browser windows in full screen, and everytime I open a workspace it is restored not in full screen.
I'm using workspaces 0.5, brave browser 1.36.109 and windows 10.
Is it possible to fix this issue? Thanks.

**Comment by 424344** [comment]
investigating this issue I found something that could be of use:
https://stackoverflow.com/questions/37644098/chrome-extension-maximize-current-window
btw, I reported the issue about full-screen , bit I really mean maximised windows, not full-screen (sorry).

**Comment by imageslr** [comment]
maybe you can try some plugins in mac, such as [rectangle](https://rectangleapp.com/). Its shortcuts are very convenient.

**Comment by 424344** [comment]
Thanks for the tip @imageslr  , but I'm running windows10.
