### ISSUE TITLE
TODO List 404

### ISSUE THREAD

**Issue by wwwerk** [vsmejkal/chrome-workspaces#16]
https://blog.frantic.im/all/todo-file-for-personal-projects/

Would like to see what plans there are for this incredibly useful extension.

**Comment by imageslr** [comment]
I found this TODO file: https://github.com/vsmejkal/chrome-workspaces/blob/master/TODO

**Comment by wwwerk** [comment]
Thank you @imageslr !

**Comment by vsmejkal** [comment]
The broken link has been fixed. Thanks.
