### ISSUE TITLE
unreachable workspace if plugin deleted

### ISSUE THREAD

**Issue by buckelieg** [vsmejkal/chrome-workspaces#28]
Steps to reproduce:
1) install extension
2) create workspace in same window
3) uninstall extension
4) install extension
5) previously created workspace is not in the list

browser: Chrome 115

**Comment by vsmejkal** [comment]
Currently this is expected behavior. Uninstalling the extension removes the workspaces data. You need to create workspaces again if reinstalled.

In future it should be solved with Issue #18.
