### ISSUE TITLE
Create a workspace from the current window

### ISSUE THREAD

**Issue by amfogor** [vsmejkal/chrome-workspaces#3]
I was quite surprised I couldn't use the current window as the basis for a new workspace.

**Comment by vsmejkal** [comment]
Thanks for the suggestion. I am planning to convert the extension to Manifest V3 and release version 1.0 that should include this feature.

**Comment by imageslr** [comment]
+1 and thanks

**Comment by vsmejkal** [comment]
Implemented in v0.5.
