### ISSUE TITLE
add context menu on tab

### ISSUE THREAD

**Issue by lazymonkey2** [vsmejkal/chrome-workspaces#36]
Hello,
is it possible to add the workspace context menu to tabs?
I mean I want to see the contenxt menu when I right click on the tab (I want to move the tab to a different workspace).

Right now I can see the context menu when I right click in the page, but I have visited some pages that contain a full page video player, and the contenxt menu is not working (right clicking does nothing, so I cannot move the tab to a different workspace).

thanks.

**Comment by vsmejkal** [comment]
Unfortunately this is not possible in Chrome.

As a workaround you can right click on the extension icon and move the tab to a different workspace from there.

Hope it helps.

**Comment by lazymonkey2** [comment]
ok, right clicking on the extension icon will be enough.
thank you!
