### ISSUE TITLE
Use shortcut to quickly switch workspaces

### ISSUE THREAD

**Issue by imageslr** [vsmejkal/chrome-workspaces#7]
Allow to configure a shortcut in chrome, to activate the extension. Such as:

![image](https://user-images.githubusercontent.com/17822028/134280139-9b35fd6b-2f28-4383-b4fe-91dbfb7ec30c.png)

For example, if I set the shortcut as `alt + f`, I can firstly press `alt + f` to activate the popup view of the extension, then I can continue to press `tab` multiple times, to focus on different workspaces in the popup. Finally, I press `enter`, to switch to the target workspace.

**Profits**: I don't have to move mouse, locate the extension icon and click it, then select a workspace and click it. All actions can be done via keyboard.

**Comment by vsmejkal** [comment]
Great suggestion, thanks! I will implement it in the next version.

**Comment by imageslr** [comment]
Thanks! But now I think that use same shortcut for activating popup and selecting a workspace, is better than use `alf + f` (active) + `tab` (select) mentioned above ----- reduce moving figures.

Maybe these shortcuts can all be customized? Depends on you :)

**Comment by vsmejkal** [comment]
Implemented in v0.5. Now you can use Alt+W and arrows to select a workspace.

**Comment by imageslr** [comment]
Great！

**Comment by imageslr** [comment]
Amend for users:

If you want to switch between chrome workspaces, you can use shortcut ``command + ` `` on macOS.

BTW, I suggest you to install [AltTab](https://alt-tab-macos.netlify.app/). This is a window switch enhancement tools on macOS. It provides preview when switch window with ``command + ` ``.
