### ISSUE TITLE
Drag to order workspaces

### ISSUE THREAD

**Issue by imageslr** [vsmejkal/chrome-workspaces#8]
Allow to drag to order workspaces in the popup window.

**Comment by imageslr** [comment]
Hi @vsmejkal , I'd like to add this feature with [sortablejs](https://github.com/SortableJS/Sortable) or other similar library. How do you think? Do you prefer to implement it with vanilla js?

**Comment by vsmejkal** [comment]
@imageslr Great! Feel free to put something together and open a new PR.

I would prefer a vanilla JS or a really tiny library like [html5sortable](https://github.com/lukasoppermann/html5sortable). Using SortableJS would double the current extension size.

**Comment by imageslr** [comment]
Sorry I was busy last month and don't have time to do this recently. 
Thank you again for such a great job.

**Comment by vsmejkal** [comment]
I plan to implement this in v0.7.

**Comment by vsmejkal** [comment]
Implemented in v0.6 by @imageslr.

**Comment by imageslr** [comment]
Great! Just need to manually update the extension: 

![image](https://user-images.githubusercontent.com/17822028/183018869-a81275b7-efe3-4b54-8a5a-08bbcd0f2f94.png)
